// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7Jb5EWU8pqA-E9J-P2vIQn-Wn7FMTY8',
    appId: '1:1049563044220:web:cc7cb99a22a271f1ccecf9',
    messagingSenderId: '1049563044220',
    projectId: 'study-timer-app-751f2',
    authDomain: 'study-timer-app-751f2.firebaseapp.com',
    storageBucket: 'study-timer-app-751f2.firebasestorage.app',
    measurementId: 'G-SDNVJVNKGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25LwJq0ndlYK40C-aipjNiq3xgJcIu2k',
    appId: '1:1049563044220:android:eed27457082ccb18ccecf9',
    messagingSenderId: '1049563044220',
    projectId: 'study-timer-app-751f2',
    storageBucket: 'study-timer-app-751f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVu8y_0chUdtzrAfSRLIfCPIQhV90MwY',
    appId: '1:1049563044220:ios:7bf4965c980c21f4ccecf9',
    messagingSenderId: '1049563044220',
    projectId: 'study-timer-app-751f2',
    storageBucket: 'study-timer-app-751f2.firebasestorage.app',
    androidClientId: '1049563044220-dde8qsnc88hp9jd8ahh64a58r5aopo5r.apps.googleusercontent.com',
    iosClientId: '1049563044220-qaieeo4e2ed5a8qkl45k8fvs8t3eptff.apps.googleusercontent.com',
    iosBundleId: 'com.pedromassango.xtimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVu8y_0chUdtzrAfSRLIfCPIQhV90MwY',
    appId: '1:1049563044220:ios:ce30cc4d89a7bfb9ccecf9',
    messagingSenderId: '1049563044220',
    projectId: 'study-timer-app-751f2',
    storageBucket: 'study-timer-app-751f2.firebasestorage.app',
    androidClientId: '1049563044220-dde8qsnc88hp9jd8ahh64a58r5aopo5r.apps.googleusercontent.com',
    iosClientId: '1049563044220-rlhshp36hnv0qoa0pgkkpvsa0ulm2r8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.xtimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7Jb5EWU8pqA-E9J-P2vIQn-Wn7FMTY8',
    appId: '1:1049563044220:web:210714eea620e615ccecf9',
    messagingSenderId: '1049563044220',
    projectId: 'study-timer-app-751f2',
    authDomain: 'study-timer-app-751f2.firebaseapp.com',
    storageBucket: 'study-timer-app-751f2.firebasestorage.app',
    measurementId: 'G-LM1EC7W46B',
  );
}
